global using Bluebird.Core;
global using Microsoft.Web.WebView2.Core;
global using muxc = Microsoft.UI.Xaml.Controls;
global using Newtonsoft.Json;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Windows.ApplicationModel;
global using Windows.ApplicationModel.Core;
global using Windows.Storage;
global using Windows.Storage.Streams;
global using Windows.System;
global using Windows.UI.Core;
global using Windows.UI.ViewManagement;
global using Windows.UI.Xaml;
global using Windows.UI.Xaml.Controls;
global using Windows.UI.Xaml.Controls.Primitives;
global using Windows.UI.Xaml.Input;
global using Windows.UI.Xaml.Markup;
global using Windows.UI.Xaml.Media.Imaging;
global using static Bluebird.Core.Globals;